### ISSUE TITLE
Kickoff | Clean Script throws ESLint errors

### ISSUE THREAD

**Issue by erwstout** [PlayPickUp/kickoff#11]
After install, ESLint complains about imports  in clean.js

![image.png](https://images.zenhubusercontent.com/5fac0c960e671a2328e890c2/fd3ebe50-3234-4f37-9905-28301e7fadce)

**Comment by erwstout** [comment]
Adding `/* eslint-disable @typescript-eslint/no-var-requires*/` to clean.js will fix the issue

**Comment by saurabhmehta1601** [comment]
This error is happening due  to rule no-vars-requires which do not allow commonjs require-export syntax .You can know more about this rule from   [here](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-require-imports.md).

It is better to not run @typescript-eslint/recommended plugin and react/recommended plugin on .js files but only on .ts and .tsx files .
You can do that using overrides in eslintconfig  .

**Comment by erwstout** [comment]
Great catch, thanks @saurabhmehta1601
