### ISSUE TITLE
Error running yarn install in lib

### ISSUE THREAD

**Issue by saurabhmehta1601** [PlayPickUp/kickoff#15]
Trying to run `yarn install ` in lib directory gives error as .git cannot be found .
![Uploading Screenshot from 2021-09-03 09-50-25.png…]()

**Comment by saurabhmehta1601** [comment]
![Screenshot from 2021-09-03 09-50-25](https://user-images.githubusercontent.com/57309205/131951333-ff345b9f-28d8-4f41-9fbe-9c62b4f2f05d.png)

**Comment by erwstout** [comment]
this is expected as the end user is installing via `npx @playpickup/kickoff their-project` and it runs the install scripts, which includes `git init`. If you're experiencing this while testing/developing on the repo, just running `git init` inside of the `lib` file will do
